apiVersion: apps/v1
kind: Deployment
metadata:
  name: primerapi
  labels:
    app: primerapi
spec:
  selector:
    matchLabels:
      app: primerapi
  template:
    metadata:
      labels:
        app: primerapi
    spec:
      containers:
      - name: primerapi
        image: danielsabana/vaca:1.3.0
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "200m"
            memory: "600Mi"
        startupProbe:
          httpGet:
            path: /saludo
            port: 8081
          initialDelaySeconds: 5
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
