name: Integracion continua
on:
  pull_request:
    branches:
      - main
      - develop
      - master
      - release
      - xxx
      - trunk
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v7
      - name: Instalar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - name: instalar gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Compilamos
        run: ./gradlew build

